
spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2

# Placeholders batch.*
#    for H2:
#batch:
#  jdbc:
#    driver: org.h2.Driver
#    url: jdbc:h2:mem:test
#    user: sa
#    password:
#    testWhileIdle: true
#    validationQuery:
#  database:
#    incrementer:
#      class: org.springframework.jdbc.support.incrementer.H2SequenceMaxValueIncrementer
#  schema:
#    script: classpath:/org/springframework/batch/core/schema-h2.sql
#  drop:
#    script: classpath:/org/springframework/batch/core/schema-drop-h2.sql

  # Non-platform dependent settings that you might like to change
  data:
    source:
      init: true
  table:
    prefix: BATCH_
